FROM node:18 AS build

WORKDIR /app

COPY package*.json ./

RUN npm install --legacy-peer-deps

#ARG REACT_APP_API_URL
#ARG REACT_APP_BACKEND_URL
#ENV REACT_APP_API_URL=$REACT_APP_API_URL
#ENV REACT_APP_BACKEND_URL=$REACT_APP_BACKEND_URL

COPY . .

RUN npm run build

FROM nginx:alpine

COPY nginx.conf /etc/nginx/nginx.conf
COPY --from=build /app/build /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
